select(2, ...).locals = {
	["Your DB has been upgraded to the new storage format."] = "Ваша БД была обновлена до нового формата хранения.",
	["Unable to restore equipment set \"%s\" to slot #%d, it does not appear to exist anymore."] = "Невозможно восстановить комплект экипировки \"%s\" в слот #%d, похоже, он больше не существует.",
	["Slash commands"] = "Команды чата",
	["Saved profile %s!"] = "Профиль %s сохранен!",
	["Restored profile %s!"] = "Профиль %s восстановлен!",
	["No profile with the name \"%s\" exists."] = "Профиль с именем \"%s\" не существует.",
	["Deleted saved profile %s."] = "Удален сохраненный профиль %s.",
	["Profile List"] = "Список профилей",
	
	["Spells \"%s\" and \"%s\" are now linked."] = "Заклинания \"%s\" и \"%s\" теперь связаны.",
	["Invalid spells passed, remember you must put quotes around both of them."] = "Переданы неверные заклинания, не забудьте заключить оба в кавычки.",
	
	["Checking item count is now enabled!"] = "Проверка количества предметов включена!",
	["Checking item count is now disabled!"] = "Проверка количества предметов отключена!",
	["Auto profile save on logout is enabled!"] = "Автосохранение профиля при выходе включено!",
	["Auto profile save on logout is disabled!"] = "Автосохранение профиля при выходе отключено!",
	["Auto macro restoration is now enabled!"] = "Автовосстановление макросов включено!",
	["Auto macro restoration is now disabled!"] = "Автовосстановление макросов отключено!",
		
	["/abs save <profile> - Saves your current action bar setup under the given profile."] = "/abs save <профиль> - Сохраняет текущую настройку панелей действий в указанный профиль.",
	["/abs restore <profile> - Changes your action bars to the passed profile."] = "/abs restore <профиль> - Изменяет панели действий согласно указанному профилю.",
	["/abs delete <profile> - Deletes the saved profile."] = "/abs delete <профиль> - Удаляет сохраненный профиль.",
	["/abs logout - Toggles auto saving of the current profile whenever you leave the world."] = "/abs logout - Включает/выключает автосохранение текущего профиля при выходе из игры.",
	["/abs list - Lists all saved profiles."] = "/abs list - Показывает список всех сохраненных профилей.",
	["/abs errors - Lists the errors that happened on the last restore (if any)."] = "/abs errors - Показывает ошибки, возникшие при последнем восстановлении (если есть).",
	["/abs macro - Attempts to restore macros that have been deleted for a profile."] = "/abs macro - Пытается восстановить удаленные макросы для профиля.",
	["/abs count - Toggles checking if you have the item in your inventory before restoring it, use if you have disconnect issues when restoring."] = "/abs count - Включает/выключает проверку наличия предмета в инвентаре перед восстановлением. Используйте, если возникают проблемы с отключением при восстановлении.",
	["/abs test <profile> - Tests restoring a profile, results will be outputted to chat."] = "/abs test <профиль> - Тестирует восстановление профиля, результаты выводятся в чат.",
	["/abs rename <oldProfile> <newProfile> - Renames a saved profile from oldProfile to newProfile."] = "/abs rename <старый_профиль> <новый_профиль> - Переименовывает сохраненный профиль.",
	["/abs link \"<spell 1>\" \"<spell 2>\" - Links a spell with another, INCLUDE QUOTES for example you can use \"Shadowmeld\" \"War Stomp\" so if War Stomp can't be found, it'll use Shadowmeld and vica versa."] = "/abs link \"<заклинание 1>\" \"<заклинание 2>\" - Связывает два заклинания. ИСПОЛЬЗУЙТЕ КАВЫЧКИ, например \"Слиться с тенью\" \"Громовая поступь\", чтобы использовать Слиться с тенью, если Громовая поступь недоступна и наоборот.",
	["/abs rank - Toggles if ABS should restore the highest rank of the spell, or the one saved originally."] = "/abs rank - Включает/выключает восстановление максимального ранга заклинания вместо изначально сохраненного.",
	
	["Unable to restore profile \"%s\", you are in combat."] = "Невозможно восстановить профиль \"%s\", вы в бою.",
	["Unable to restore item \"%s\" to slot #%d, you on the Arena Tournament Realms and attempting to restore that item would cause a disconnect."] = "Невозможно восстановить предмет \"%s\" в слот #%d, вы на турнирных серверах Арены, попытка восстановить этот предмет вызовет отключение.",
	["Unable to restore item \"%s\" to slot #%d, cannot be found in inventory."] = "Невозможно восстановить предмет \"%s\" в слот #%d, не найден в инвентаре.",
	["Unable to restore macro id #%d to slot #%d, it appears to have been deleted."] = "Невозможно восстановить макрос #%d в слот #%d, похоже, он был удален.",
	["Unable to restore spell \"%s\" to slot #%d, it does not appear to have been learned yet."] = "Невозможно восстановить заклинание \"%s\" в слот #%d, похоже, оно еще не изучено.",
	
	["No errors found!"] = "Ошибок не найдено!",
	["Errors found: %d"] = "Найдено ошибок: %d",
	["Restored profile %s, failed to restore %d buttons type /abs errors for more information."] = "Восстановлен профиль %s, не удалось восстановить %d кнопок, введите /abs errors для подробностей.",
	
	["Miscellaneous"] = "Разное",
	["Unable to restore companion \"%s\" to slot #%d, it does not appear to exist yet."] = "Невозможно восстановить питомца \"%s\" в слот #%d, похоже, он еще не существует.",
	["Unable to restore macros, you already have %d global and %d per character ones created."] = "Невозможно восстановить макросы, у вас уже создано %d глобальных и %d персональных макросов.",
	["Cannot restore profile \"%s\", you can only restore profiles saved to your class."] = "Невозможно восстановить профиль \"%s\", вы можете восстанавливать только профили, сохраненные для вашего класса.",
	
	-- Classes
	["UNKNOWN"] = "Неизвестно",
	["WARRIOR"] = "Воин",
	["DRUID"] = "Друид",
	["PALADIN"] = "Паладин",
	["SHAMAN"] = "Шаман",
	["WARLOCK"] = "Чернокнижник",
	["PRIEST"] = "Жрец",
	["MAGE"] = "Маг",
	["HUNTER"] = "Охотник",
	["ROGUE"] = "Разбойник",
	["DEATHKNIGHT"] = "Рыцарь смерти",
	
	["Are you sure you want to delete profile %s?"] = "Вы уверены, что хотите удалить профиль %s?",
	["Delete Profile"] = "Удаление профиля",
	["This action cannot be undone."] = "Это действие нельзя отменить.",
	["Unable to restore mount \"%s\" to slot #%d"] = "Невозможно восстановить средство передвижения \"%s\" в слот #%d",
} 